name: Hello Debug Workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allows manual triggers

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello for debugging"
